### ISSUE TITLE
Koodikatselmointi 1

### ISSUE THREAD

**Issue by madhaanr** [jhamberg/wordz-solver#1]
Sanasampo vaikuttaa todella hyvin toteutetulta projektilta ja noudattaa hyvin clean code periaatteita. Toiminnallisuus on myös jaettu riittävän pieniin osiin ja koodi on helposti luettavaa. 

-Olioiden nimet esim. Sampo luokassa voisivat olla pitempiä kuin yksi kirjain. Toisaalta oliot on eri luokissa järjestelmällisesti nimetty lyhyin nimin.
-Luokkien, pakettien ja muuttujien nimissä on käytetty sekä suomea että englantia. Joissakin tapauksissa tämä varmasti selkeyttää koodia mutta esim Ruudukkoluokan validate metodin nimeäisin suomeksi.
-Lisäisin jonkun tavan nähdä miten pitkän sanan olen kirjoittanut "ruudukon valinta" ikkunaan. Koska kaikki muut käyttäjälle näkyvät tekstit ovat englanniksi niin muuttaisin myös tämän ikkunan tekstit englanniksi.
-Ehdotan että laitat ylärajan syötetekstin pituudelle, koska käyttöliittymän koko on kiinteästi rajattu ja esim. 11_11 ruudukosta ei enää erota kaikkia kirjaimia vaan niiden tilalla on "...".
-Ruudukko luokassa on seuraava vertailu: Pattern.compile("^[a-zA-Z0-9äöåÅÄÖ]_$", Pattern.CASE_INSENSITIVE);. 
Koska syötteessä ei saa olla ääkkösiä(tulee ihan asiallinen virheilmoitus) eikä sanassa voi olla numeroita niin kysyisin, että tekeekö tämä vertailu sitä mitä halutaan? 

Latasin koodin katselmoitavaksi 10.2. 11:33.

**Comment by jhamberg** [comment]
Kiitos palautteesta! 

Selkeytin nyt metodien ja muuttujien nimeämistä, korjasin kieliongelmat ja rajasin ruudukon maksimikoon. 
Patternissa oli käynyt ajattelumoka ja validoinnin pitäisi nyt toimia halutusti. 

Päivitin ohjelmakoodin 12.2. klo. 13:36.

![korjaukset_katselmointi](https://f.cloud.github.com/assets/3019559/148617/f1d692ba-7509-11e2-9f23-ba9555bc9c18.png)
